migration_storage:
  storage_type: "postgres" # boltdb|postgres
  dsn: "postgres://postgres:postgres@dbpg:5432/migrago?sslmode=disable"
  schema: "public"
  path: "example/data/migrations.db"

projects:
  project1:
    migrations:
    - example_database_postgresql: example/migrations/postgres
  
databases:
  example_database_postgresql:
    type: postgres
    dsn: "postgres://postgres:postgres@localhost2/postgres?sslmode=disable"
    schema: "test"
  example_database_clickhouse:
    type: clickhouse
    dsn: "tcp://host1:9000?username=user&password=qwerty&database=clicks"
